#!/usr/bin/env python3
"""
Convert scripts/music/output/musicStructures.json into src/data/musicStructures.js
so the web app can import a synchronous ES module without runtime fetch.

Run: make web-sync-music-data
"""
from __future__ import annotations

import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
JSON_PATH = REPO / 'scripts' / 'music' / 'output' / 'musicStructures.json'
OUT_DIR = REPO / 'src' / 'data'
OUT_FILE = OUT_DIR / 'musicStructures.js'

if not JSON_PATH.exists():
    raise SystemExit(f"Missing JSON: {JSON_PATH}")

OUT_DIR.mkdir(parents=True, exist_ok=True)

data = json.loads(JSON_PATH.read_text(encoding='utf-8'))
content = (
    "// Auto-generated by make web-sync-music-data from scripts/music/output/musicStructures.json\n"
    "// Do not edit this file by hand; re-run the exporter + sync instead.\n\n"
    f"export const musicStructures = {json.dumps(data, indent=2)};\n\n"
    "export const changeRingingLibrary = musicStructures.changeRingingLibrary;\n"
    "export const permutationFamilies = musicStructures.permutationFamilies;\n"
    "export const symmetricGroupCatalog = musicStructures.symmetricGroupCatalog;\n"
    "export const musicStructuresGeneratedAt = musicStructures.generatedAt;\n\n"
    "export default musicStructures;\n"
)
OUT_FILE.write_text(content, encoding='utf-8')
print(f"[OK] Wrote {OUT_FILE.relative_to(REPO)} from {JSON_PATH.relative_to(REPO)}")
